### ISSUE TITLE
waitForTcpPorts too fast for the tests

### ISSUE THREAD

**Issue by avillev** [avast/gradle-docker-compose-plugin#151]
Hello,

I have a problem in a very specific usefase with the plugin.

My files:

```
version: '2'
services:
  rmq:
    build:
      context: ""
      dockerfile: rmq.docker
    ports:
      - "5672:5672"
      - "15672:15672"
```
```
FROM rabbitmq:3.6.15-management
COPY configure-node.sh /
RUN chmod u+x /configure-node.sh
CMD ["/configure-node.sh"]
```
```
#!/bin/bash

set -e
set -x
set -m

/docker-entrypoint.sh rabbitmq-server &

sleep 15

# Setup the test exchange and queues
rabbitmqadmin declare exchange name=test-exchange type=fanout
rabbitmqadmin declare queue name=test-queue durable=false
rabbitmqadmin declare binding source=test-exchange destination=test-queue

fg 1
```

What happens is that the plugin is detecting the server to be ready before the configuration command lines are done:

> 10:58:15 TCP socket on 172.20.0.1:15672 of service 'rmq_1' is ready
> 10:58:16 TCP socket on 172.20.0.1:5672 of service 'rmq_1' is ready

As a consequence, the tests are executed before the rabbitmqadmin commands and they fail.

Am i doing something wrong here ?
