### ISSUE TITLE
Random TCP port is getting assigned for the container which starts in a second

### ISSUE THREAD

**Issue by chit786** [avast/gradle-docker-compose-plugin#152]
Docker compose file : 

```
version: "2"

services:
  ldap:
    build: ldap
    ports:
      - 32769:389
      - 32768:636
    volumes:
      - ./ldap/ldap2.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    command:
      - --copy-service
  jenkins:
    build: jenkins
    ports:
      - 18080:8080
      - 50000:50000
  mail:
    build: mail
    ports:
      - 11080:80
      - 225:25
  xlr:
    build:
      context: xlr
    ports:
      - 1166:1166
```

the mail service takes less than 2 seconds to start the container and expose ports but composeup command executes it after test of the services are up i.e. xlr, jenkins,ldap and somehow it assigns a random port everytime and hangs on : 
```
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
Waiting for TCP socket on localhost:32809 of service 'mail_1' (TCP connection on localhost:32809 of service 'mail_1' was disconnected right after connected)
```

Any idea why this is happening. The service 'mail ' is not even exposing the port.
