### ISSUE TITLE
Bug: wrong input parsed when finding container ids

### ISSUE THREAD

**Issue by cecton** [avast/gradle-docker-compose-plugin#171]
(Following #170 ) I finally found my problem. Some environment variable were not set and, because of that, the list of container ids got corrupted.

Here is the command docker inspect that makes the whole process fail:
```
docker inspect The JS_ADDRESS variable is not set. Defaulting to a blank string. The DGC_JAVA_OPTS variable is not set. Defaulting to a blank string. ed3f18afcad7017e375a34a79f6ddb0e7c31890739ceec175884929b611d85f4 ae9ef16d8751f48ec83801fc461814c4ccad8ae4cf3eb305300930b7922c3b1d
```

I double checked and the "variable is not set" come from Docker Compose, probably from the command `docker-compose ps -q` that you run to find the ids of the containers. So I suppose the "execute" there is parsing the STDERR with the STDOUT.

**Comment by augi** [comment]
Could you please give an example of docker-compose.yml that produces this kind of error? Thanks!

**Comment by cecton** [comment]
Here you go:

(See how WORLD isn't defined and shouldn't be defined to trigger the bug)

```
version: "2"
services:
  service1:
    image: busybox
    environment:
      - HELLO=${WORLD}
    command: "echo Hello World"
  service2:
    image: busybox
    command: "echo Hello World"
```
