### ISSUE TITLE
env variable substitution in dockerfiles

### ISSUE THREAD

**Issue by iluxa-com** [avast/gradle-docker-compose-plugin#193]
I have a following docker-compose.yml
```
    service1:
        build:
            dockerfile: dockerfile

    serice2:
        image: service2-image:$VERSION
```
dockerfile:
```
FROM service1-image:$VERSION
...
```
and in my build.gradle
```
...
dockerCompose {
    environment.put 'VERSION', image_version
...
```
The VERSION variabe works fine in the docker-compose file, but it doesn't in dockerfile (
My build fails with an error:
```
':tests:integration:composeUp'. java.lang.RuntimeException: Exit-code 1 when calling docker-compose, stdout: Step 1/5 : FROM service1-image:$VERSION
```
Could you suggest anything?
TIA
