### ISSUE TITLE
Dockerfile with Healthcheck is indefinitely waiting to become healthy not allowing gradle to proceed with other tasks

### ISSUE THREAD

**Issue by smian** [avast/gradle-docker-compose-plugin#194]
Hello, great plugin but I have an issue that's keeping me from using it widely. 

In the dockerfile for the backend springboot app, I have a standard healthecheck directive:

`
HEALTHCHECK CMD curl --fail http://localhost:5000/api/actuator/health || exit 1`

When I use ComposeUp, postgres starts up fine and backend starts up fine as far as Springboot startup but the following keeps printing and won't let me run my integration tests:

```
Waiting for backend_1 to become healthy (it's unhealthy)
Waiting for backend_1 to become healthy (it's unhealthy)
...
```

Here's my docker-compose file. If I add `healthcheck: disable: true` then everything seems to be fine but I would like to keep the docker-compose file consistent, instead of having another docker-compose file just for using gradle ComposeUp.

```
version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend-api:latest
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - 5000:5000
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/xolvdb
      - DB_SCHEMA=backend-api
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=a1111111
    volumes:
      - /data/backend-api
#    healthcheck:
#      disable: true 

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a1111111
      - POSTGRES_DB=backenddb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: null
```

Appreciate your help!
