### ISSUE TITLE
exposeAsSystemProperties doesn't seem to work?

### ISSUE THREAD

**Issue by NotTheEconomist** [avast/gradle-docker-compose-plugin#221]
Maybe I'm just doing this wrong, but I can't seem to access the exposed container information in my tasks. My minimal example follows:

```gradle
// build.gradle
plugins {
    id 'com.avast.gradle.docker-compose' version '0.10.9'
}

dockerCompose {
    useComposeFiles = ['docker-compose.yml']
}

task myTask(type: Task) {
    doFirst {
        println System.properties.get('nginx.host', 'not found')
    }
}

dockerCompose.isRequiredBy(myTask)
```

```yaml
# docker-compose.yml
version: '2'
services:
    nginx:
        image: 'nginx:stable'
        ports:
            - 80
```

Run this with `gradlew myTask` and I expect to see `localhost` printed, but instead see `not found`. Shouldn't `dockerCompose.isRequiredBy(myTask)` expose that system property?
