### ISSUE TITLE
How to remove volumes?

### ISSUE THREAD

**Issue by alexromero88** [avast/gradle-docker-compose-plugin#224]
Hi,

I'm using the version: '3.6' for docker-compose yaml. My volumes are created when starting up the services, but I can't find an easy way to remove all the volumes, as they are defined independently:

```
volumes:
  common-volume:
  full-service-volume:
  public-volume:
  ops-volume:
  papi-volume:
  papi-modules-volume:
  cps-volume:
```

Does the plugin support removing this volumes somehow?

Thanks

**Comment by augi** [comment]
Hi, thanks for your question.

This plugin automatically removes volumes when `composeDown` task is executed. To be more specific, it executes `docker-compose down --volumes` command.

You can disable this behavior by changing `dockerCompose.removeVolumes` to `false` (default value is `true`).

**Comment by alexromero88** [comment]
Well, I'm pretty sure it's not removing the volumes for me. I know that the way volumes are defined changed from version '2' to '3' in docker compose, can that affect somehow? For example:

```
version: '3.6'
services:
    file-sync-common: # Service to sync common classes to the containers, so jrebel can reload
      container_name: file-sync-common
      image: docker.intuit.com/small-business/onlinepayroll/cicd/skysthelimit/file-sync:1.2
      volumes:
        - $HOME/dev/iop/Common:/source:delegated
        - common-volume:$HOME/dev/iop/Common:delegated
      healthcheck:
        test: test -e /initSync.txt
        timeout: 1s
        interval: 5s
        retries: 130
        start_period: 10s
      environment:
        - SYNC_DESTINATION=$HOME/dev/iop/Common
        - SYNC_MAX_INOTIFY_WATCHES=30000
        - |
          SYNC_EXTRA_UNISON_PROFILE_OPTS=
          path = gradleBuild/classes/
          path = gradleBuild/resources/
      privileged: true
volumes:
  common-volume:

networks:
    payroll-net:
        driver: bridge
```
Today, the plugin does not remove the volume `common-volume` for me
