### ISSUE TITLE
Discover HOST info only needed for `settings.waitForTcpPorts` ON

### ISSUE THREAD

**Issue by andresvia** [avast/gradle-docker-compose-plugin#230]
@augi 

I'm new to this project, if my understanding is correct, the "host" discovery happening, in `getContainerHost` is only needed if `settings.waitForTcpPorts` is ON, otherwise is not needed, I have a complex network setup, and I'm getting "Gateway cannot be obtained", I have comprehensive actual docker healthchecks that work perfect for me. I rather avoid the attempts to discover the docker host if is actually not going to be required to determine healthyness.

I may be able to send a PR later when I have some time, want to confirm that the approach/idea makes sense.

Thanks.

https://github.com/avast/gradle-docker-compose-plugin/blob/9375f1723e44c24548a65e986ac3547fe6c68c92/src/main/groovy/com/avast/gradle/dockercompose/DockerExecutor.groovy#L98

**Comment by augi** [comment]
Hello, the `host` is actually used everywhere. Or to be more specific - the plugin itself uses the discovered `host` value just for waiting for TCP ports. But this value is exposed to anyone and it is typically used (with the exposed port) as the address to access a service (e.g. running Postgres).

Could you please share how the `network` part of `docker inspect` output looks like in your case? Maybe this plugin doesn't handles a valid situation.

As hotfix, if you don't want to end up with the `Gateway cannot be obtained` error, set `SERVICES_HOST` environment variable before running Gradle.

**Comment by andresvia** [comment]
@augi , I did:

```
docker inspect $(docker-compose --file compose.conf ps --quiet) --format '{"{{.Id}}":{{json .NetworkSettings}}}' | jq .
```

See attachments. [networksetting.zip](https://github.com/avast/gradle-docker-compose-plugin/files/4571491/networksetting.zip)

On a dev box (Mac OSX) and on the CI environment, in MacOS X, composeUp works in the CI environment fails.

the plugin config is:

```
dockerCompose {
    useComposeFiles = ['compose.conf']
    waitForTcpPorts = false
    projectName = 'gb-workflows'
}
```

Both files looks identical to me, it seems like the mac logic short-circuits the discovery of host.

Let me know if you need more info to debug.

I guess this piece of information may be useful too, in docker-compose file I'm using this network configuration for all containers except "localbind".

```
    network_mode: service:localbind
```

This is a network mode in compose that emulates what the `docker run --network container:foo` 
does.

I guess this compose file may help you reproduce.

```
cat docker-compose.yaml 
version: '2.1'
services:
  localbind:
    image: alpine
    entrypoint: /bin/sleep
    command: infinity
    ports:
      - 8081:8081 # server1
      - 8082:8082 # server1
  server1:
    image: python:2
    command: python -m SimpleHTTPServer 8081
    network_mode: service:localbind
  server2:
    image: python:2
    command: python -m SimpleHTTPServer 8082
    network_mode: service:localbind
```

The way I'm harnessing this compose file is the following (not quite just as an example).

```
docker exec -it $(docker-compose ps --quiet server1 ) curl -I http://127.0.0.1:8082/
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/2.7.18
Date: Sun, 03 May 2020 20:12:03 GMT
Content-type: text/html; charset=UTF-8
Content-Length: 768
```

compose service server1, "sees" compose service server2, as if they are in the same host.

This way all services communicate with each other as if they are running in the same host, and this is also seamless for devs that expect everything running on localhost.

Thanks @augi

**Comment by andresvia** [comment]
This is a contrived example but I think makes my point.

Assume the following docker compose file:

```
version: '3.0'
services:
  localbind:
    image: alpine
    entrypoint: /bin/sleep
    command: infinity
    ports:
      - 127.0.0.1:8080:8080 # for me HTTP
      - 192.168.65.3:8080:8443 # for peers on the same network HTTPS
  server1:
    image: python:2
    # assume python module SimpleSecureHTTPServer is a thing
    command: "python -m SimpleHTTPServer 8080 & python -m SimpleSecureHTTPServer 8443 & wait"
    network_mode: service:localbind
```

Then you could do

`curl -I http://127.0.0.1:8080/`

HTTP for yourself and for peers on the same network HTTPS

`curl --insecure -I https://192.168.65.3:8080/`

The "Ports" "NetworkSettings" inspect section for "localbind" is:

```
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "8080"
                    }
                ],
                "8443/tcp": [
                    {
                        "HostIp": "192.168.65.3",
                        "HostPort": "8080"
                    }
                ]
            }
```
