### ISSUE TITLE
health state is ready and disconnects right after.

### ISSUE THREAD

**Issue by danielptm** [avast/gradle-docker-compose-plugin#234]
Hello. Thank you providing this plugin. It seems fantastic but am having trouble getting it to work correctly it seems. I followed these instructions for setting up the plugin. https://plugins.gradle.org/plugin/com.avast.gradle.docker-compose. It is pointing at a docker-compose file that looks like this:

```
version: '3'
services:
  infrastructure:
    build: ""
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    links:
    - localstack
  localstack:
    image: localstack/localstack
    ports:
    - "4567-4584:4567-4584"
    environment:
    - SERVICES=s3:4572,sns:4575,sqs:4576,dynamodb:4569
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 1m30s
      timeout: 10s
      retries: 10

```
However when in run ./gradlew integrationTest it looks like composeUp is starting but then fails because I see this terminal output.
```
...
Waiting for localstack_1 to become healthy (it's starting)
localstack_1 health state reported as 'healthy' - continuing...
Probing TCP socket on localhost:4567 of service 'localstack_1'
Waiting for TCP socket on localhost:4567 of service 'localstack_1' (TCP connection on localhost:4567 of service 'localstack_1' was disconnected right after connected)
```
Are there any thoughts on how to fix this? (I'm on MBP mojave)
