### ISSUE TITLE
Containers that do not exist are not created

### ISSUE THREAD

**Issue by SJrX** [avast/gradle-docker-compose-plugin#243]
Given the following gradle file:

```
plugins {
	id "com.avast.gradle.docker-compose" version "0.12.1"
}

dockerCompose {
	projectName = null
	stopContainers = false
}

task hello {
	doFirst {
		println("Hello");
		println(dockerCompose.startedServices)
	}
}

dockerCompose.isRequiredBy(hello)

apply plugin: 'docker-compose'

task redisAOnly {
	doFirst {
		dockerCompose.startedServices = ['redisA']
	}
}

composeUp.mustRunAfter('redisAOnly')
````

and the following  docker-compose file

```
version: '3'
services:
  redisA:
    image: "redis:alpine"
    ports:
      - 10001:6379
  redisB:
    image: "redis:alpine"
    ports:
      - 10002:6379
```

Note: I think this is the same bug as bug #237 

I would expect the following series of commands to bring up both docker containers:

```
./gradlew redisAOnly hello
./gradlew hello
```

Instead of the second run, it simply says:

```
> Task :composeUp
Cached services infos loaded while 'stopContainers' is set to 'false'.
+----------+----------------+---------------------+
| Name     | Container Port | Mapping             |
+----------+----------------+---------------------+
| redisA_1 | 6379           | 192.168.240.1:10001 |
+----------+----------------+---------------------+

> Task :hello
Hello
[]
```

The reason to use projectName = null, is so that it's easier to work with the set of contaners with docker-compose, and not have to supply the -p argument.
