### ISSUE TITLE
Referencing Dynamic Env Vars in Startup / Local Env

### ISSUE THREAD

**Issue by wesleyk** [avast/gradle-docker-compose-plugin#248]
Hey folks,

Great project! Couple questions regarding the dynamic env vars that are set based on provisioned ports for services.

1. Are we able to reference these in our local environment? The env var looks to only be set on the provisioned process, is there a suggested way to reference the hosts/ports outside the process? 
2. If a service has a dependency on another service, is there a way to reference the dependency's host within the service's command? As an example below, provisioning Dynamo DB and having a separate dependency to run a dynamo command:

```
services:
  dynamo:
      image: amazon/dynamodb-local:1.13.1
      ports:
        - 8000
      command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  greeter-dynamo-tables:
    image: amazon/aws-cli
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
    command:
      - "dynamodb"
      - "create-table"
     ... // other flags
      - $DYNAMO_HOST // will not be set
    depends_on: [dynamo]
```

My hunch is that the host wouldn't be available at this point, and we should opt instead to defer inferring any dynamic portions of the command until after the services are "running".

Thank you!
