### ISSUE TITLE
How to remove volumes of nested service

### ISSUE THREAD

**Issue by FidasL** [avast/gradle-docker-compose-plugin#297]
Hello. I have got a problem with removing volumes of nested service. 

<details>
  <summary>My docker-compose file</summary>
  
```
version: '3.5'
services:
  postgres:
    image: "postgres:13"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
volumes:
  postgres_data:
```
</details>

I am using postgres container in tests. 

<details>
  <summary>Example of build.gradle file</summary>
  
```
dockerCompose {
    useComposeFiles = ["${project.rootDir}/docker/docker-compose.yml"]
    postgres {
        useComposeFiles = ["${project.rootDir}/docker/docker-compose.yml"]
        startedServices = ['postgres']
    }
}

test {
    dependsOn postgresComposeUp
    doFirst {
            dockerCompose.postgres.exposeAsEnvironment(test) // expose environment variables from running container
            def host = environment.get("POSTGRES_HOST")
            def port = environment.get("POSTGRES_TCP_5432")
            tasks.create('migratePostgres', JavaExec) { // migrate database
                 ...use liquibase to migrate database...
            }.exec()
    }
    finalizedBy postgresComposeDown
}
```
</details>

On the end of test task, created container is stopped, but when I inspect volumes with `docker volume ls`, there is always volume created by nested service. I want to remove volume always on `postgresComposeDown` command. 

<details>
  <summary>Example of postgresComposeDown output</summary>
  
```
> Task :project:postgresComposeDown
Stopping 10ab639ef5f21e43b89cb4cc04dd5483_project_postgres_postgres_1 ... 
Stopping 10ab639ef5f21e43b89cb4cc04dd5483_project_postgres_postgres_1 ... done
Removing 10ab639ef5f21e43b89cb4cc04dd5483_project_postgres_postgres_1 ... 
Removing 10ab639ef5f21e43b89cb4cc04dd5483_project_postgres_postgres_1 ... done
Going to remove 10ab639ef5f21e43b89cb4cc04dd5483_project_postgres_postgres_1
```
</details>
