### ISSUE TITLE
Add support of Docker buildKit(buildx)

### ISSUE THREAD

**Issue by logabot** [avast/gradle-docker-compose-plugin#308]
My build.gralde
```
...
dockerCompose {
    stopContainers = true // default is true
    removeContainers = true // default is true
    captureContainersOutput = false // default is false, перехват логов из контейнеров в лог сборки
    buildAdditionalArgs = ['--force-rm']
    removeVolumes = true // default is true
    removeOrphans = true
    forceRecreate = false
    noRecreate = false
    environment.put 'DOCKER_BUILDKIT', "1"
    environment.put 'COMPOSE_DOCKER_CLI_BUILD', "1"
```
docker-compose.yaml
```yaml
services:
  scheduler:
    hostname: ${HOSTNAME}:docker-scheduler
    build:
      context: .
      dockerfile: Dockerfile
      target: run-e2e-custom
      args:
    volumes:
      - "${PROJECT_DIR_VOLUMES}/test-end-to-end/build/logs:/logs"
      - "${PROJECT_DIR_VOLUMES}/test-end-to-end/src/test/resources:/config"
    ports:
      - "0244:1044"
    container_name: tests-scheduler
```
part of Dockerfile
```dockerfile
FROM gradle-common as build-scheduler

RUN \
  --mount=type=cache,id=gradle,target=/home/gradle/gradle-user-home \
  gradle clean :end-to-end:test 
```
Gradle return: 
```
> Task :test-end-to-end:composeUp FAILED
 :test-end-to-end:composeUp (Thread[Execution worker for ':',5,main]) completed. Took 5.588 secs.
 Service 'scheduler' failed to build: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
```
how to enable docker buildKit???
