### ISSUE TITLE
myTaskComposeDown doesn't stop dependant services

### ISSUE THREAD

**Issue by henrik242** [avast/gradle-docker-compose-plugin#318]
When I execute `featureTestComposeUp`, `myWeb` starts together with its dependants `api` and `integration`.  But `featureTestComposeDown` only takes down `myWeb` and leaves `api` and `integration` running.

Is there a way to get composeDown to take down the dependants as well, the same was as `docker-compose -p foo down` would?

`build.gradle.kts`:
```
configure<ComposeExtension> {
    createNested("featureTest").apply {
        projectName = "foo"
        environment.putAll(
            mapOf(
                "SOME_ENVIRONMENT" to "local",
            )
        )
        startedServices.set(listOf("myWeb"))
    }
```

`docker-compose.yml`:
```
    integration:
        build:
            context: ../integration
        image: example.com/foo/integration

    api:
        depends_on:
            - integration
        build:
            context: ../api
        image: example.com/foo/api

    myWeb:
        depends_on:
            - api
        build:
            context: .
        image: example.com/foo/my-web
```

I see that gradle-docker-compose-plugin doesn't actually issue `down`, but a selective `stop` and `rm`: 
```
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /bar/my-web Command: /usr/local/bin/docker-compose -p foo version --short
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /bar/my-web Command: /usr/local/bin/docker-compose --ansi never -foo pp stop --timeout 10 myWeb
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /bar/my-web Command: /usr/local/bin/docker-compose --ansi never -p foo rm -f -v myWeb
Successfully started process 'command '/usr/local/bin/docker-compose''
```
