### ISSUE TITLE
invalid tag

### ISSUE THREAD

**Issue by NikkyAI** [avast/gradle-docker-compose-plugin#372]
when using 

```yaml
services:
  test_elasticsearch:
    build:
      context: .
      # adds the icu plugin; we have it in elastic cloud
      dockerfile: Dockerfile_elasticsearch
```

it seems like the tag is created with invalid characters eg. `-`

```
invalid tag "a5b81cad74ed57d092b0eac4deb9fecf_formation-graphqlapi_-test_elasticsearch": invalid reference format
```
