### ISSUE TITLE
Recreate the container if a volume file changed

### ISSUE THREAD

**Issue by bwaldvogel** [avast/gradle-docker-compose-plugin#444]
I have a Docker Compose service that mounts some project files as volume into the container

```yaml
services:
  my-service:
    …
    volumes:
      - ./my-config1.yaml:/path/in/container/my-config1.yaml:ro
      - ./my-config2.yaml:/path/in/container/my-config2.yaml:ro
```

To the best of my knowledge, `docker compose up my-service` does not restart the container if it’s already up and running, even if `my-config1.yaml` or `my-config2.yaml` changed.

Since we are using Gradle with the gradle-docker-compose-plugin anyway, I would like to leverage Gradle to track input file changes and let trigger the Docker container recreation if necessary.

Is there a recommended way to achieve this or does even `gradle-docker-compose-plugin` support this feature out-of-the-box?
